version: "3"
services:
  backupserverdaemon:
    image: ghcr.io/oliverabraham/backupserverdaemon/backupserverdaemon:latest
    container_name: backupserverdaemon
    ports:
      - 32080:80
    volumes:
      - /home/pi/backupserverdaemon/appsettings.hjson:/opt/appsettings.hjson
      - /srv:/mnt
    restart: unless-stopped
